# Only Dockerize
name: cd

on:
  create:
    tags:
      - "v*"
jobs:
  image-push:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.ACCESS_TOKEN }}
    
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          ref: main
      # tag v0.0.1 -> RELEASE_VERSION = 0.0.1
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      # 0.0.1 -> 001
      - name: Find Suffix string
        run: |
          echo "SUFFIX=${VERSION//./}" >> $GITHUB_ENV
        env:
          VERSION: ${{ env.RELEASE_VERSION }}

      - name: Set up docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.ACCESS_TOKEN }}

      # Ssuwani -> ssuwani for ghcr naming rule
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Experiment Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: dockerfile
          push: true
          tags: ghcr.io/${{ env.OWNER_LC}}/train-mnist:${{ env.RELEASE_VERSION}}

      - name: run Experiment Pipeline
        run: |
          curl -u ":$TOKEN" \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/ssuwani/experiment-pipeline/actions/workflows/cd.yml/dispatches \
            -d '{"ref": "master", 
                "inputs": {
                    "RELEASE_VERSION": "${{env.RELEASE_VERSION}}"}
            }'
          
      # - name: Setup Kustomize
      #   uses: imranismail/setup-kustomize@v1

      # - name: Set new image tag
      #   run: |
      #     cd deployments/experiment/overlays/dev
      #     kustomize edit set image ghcr.io/${{ env.OWNER_LC }}/train-mnist:${{ env.RELEASE_VERSION }}
      #     kustomize edit set image ghcr.io/${{ env.OWNER_LC }}/slack-alert:${{ env.RELEASE_VERSION }}
      #     kustomize edit set namesuffix -- -${{env.SUFFIX}}
      #     git config --global user.name ${{ github.repository_owner }}
      #     git config --global user.email "jsuwan961205@gmail.com"
      #     git add .
      #     git commit -m 'Publish new version ${{ env.RELEASE_VERSION }} to dev'
      #     git push -u origin master
